# Generated by Django 2.0.5 on 2018-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='scope',
            field=models.CharField(choices=[('PR', 'Private'), ('FR', 'Friends'), ('PU', 'Public')], default='PR', max_length=2),
            preserve_default=False,
        ),
    ]
