# Generated by Django 2.0.5 on 2018-08-05 23:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_collection_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='songOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
