# Generated by Django 2.0.5 on 2018-08-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20180806_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='collections',
            field=models.ManyToManyField(blank=True, to='songs.Collection'),
        ),
    ]
