# Generated by Django 2.0.5 on 2018-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20180806_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='scope',
            field=models.CharField(choices=[('PR', 'Private'), ('FR', 'Friends'), ('PU', 'Public')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='song',
            name='scope',
            field=models.CharField(choices=[('PR', 'Private'), ('FR', 'Friends'), ('PU', 'Public')], default='PR', max_length=2),
        ),
    ]
