# Generated by Django 2.0.5 on 2018-08-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20180806_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='songs', to='songs.Collection'),
        ),
    ]
