# Generated by Django 2.0.5 on 2018-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_auto_20180806_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='formatVersion',
            field=models.IntegerField(default=1),
        ),
    ]
