# Generated by Django 2.0.5 on 2018-08-06 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20180806_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='songOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
