# Generated by Django 2.0.5 on 2018-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_auto_20180806_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='collections',
        ),
    ]
