# Generated by Django 2.0.5 on 2018-08-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_remove_song_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='songs.Collection')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='songs.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.CollectionPage', to='songs.Collection'),
        ),
    ]
