# Generated by Django 2.0.5 on 2018-09-29 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0017_auto_20180823_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Binder',
        ),
        migrations.RenameModel(
            old_name='CollectionPage',
            new_name='BinderPage',
        ),
        migrations.RenameField(
            model_name='binderpage',
            old_name='collection',
            new_name='binder',
        ),
        migrations.RemoveField(
            model_name='song',
            name='collections',
        ),
        migrations.AddField(
            model_name='song',
            name='binders',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.BinderPage', to='songs.Binder'),
        ),
    ]
