# Generated by Django 2.1.1 on 2018-09-29 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_auto_20180929_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='songOrder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
